In [2]:
import numpy as np
import random

In [4]:
m_0 = 31
c_0 = 3
x_00 = 1
n = 30

In [308]:
iteration_0 = np.empty(n)
iteration_0[0] = x_00
for i in range(1, n):
    iteration_0[i] = iteration_0[i-1] * c_0

In [309]:
permutation_0 = np.empty(n)
for i in range(n):
    permutation_0[i] = iteration_0[i] - m_0 * (int(iteration_0[i] / m_0))

In [310]:
m_1 = 17
c_1 = 3
x_01 = 1
n = 30

In [311]:
iteration_1 = np.empty(n)
iteration_1[0] = x_01
for i in range(1, n):
    iteration_1[i] = iteration_1[i-1] * c_1

In [312]:
permutation_1 = np.empty(n)
for i in range(0, n-14):
    permutation_1[i] = iteration_1[i] - m_1 * (int(iteration_1[i] / m_1))
for i in range(n-14, n-8):
    permutation_1[i] = permutation_1[i - 16] + 16
for i in range(n-8, n-7):
    permutation_1[i] = permutation_1[i - 15] + 16
for i in range(n-7, n):
    permutation_1[i] = permutation_1[i - 14] + 16

In [313]:
permutation_1

array([ 1.,  3.,  9., 10., 13.,  5., 15., 11., 16., 14.,  8.,  7.,  4.,
       12.,  2.,  6., 17., 19., 25., 26., 29., 21., 27., 30., 24., 23.,
       20., 28., 18., 22.])

In [22]:
u_1 = np.empty(n)
for i in range(0, 5):
    u_1[i] = (random.uniform(0,1))/6
for i in range(5, 10):
    u_1[i] = (random.uniform(0,1) + 1)/6
for i in range(10, 15):
    u_1[i] = (random.uniform(0,1) + 2)/6
for i in range(15, 20):
    u_1[i] = (random.uniform(0,1) + 3)/6
for i in range(20, 25):
    u_1[i] = (random.uniform(0,1) + 4)/6
for i in range(25, n):
    u_1[i] = (random.uniform(0,1) + 5)/6

array([0.08553115, 0.09349406, 0.03957581, 0.14140139, 0.03680971,
       0.2747202 , 0.16907717, 0.23457352, 0.30597327, 0.30646375,
       0.33498457, 0.44208602, 0.34316831, 0.45438164, 0.44520322,
       0.53542896, 0.6608148 , 0.51978669, 0.66482108, 0.5102033 ,
       0.66719571, 0.79048934, 0.69717014, 0.75183286, 0.71249324,
       0.88227682, 0.98377507, 0.93266857, 0.91565244, 0.88759982])

In [315]:
u_2 = np.empty(n)
for i in range(0, 5):
    u_2[i] = (random.uniform(0,1))/6
for i in range(5, 10):
    u_2[i] = (random.uniform(0,1) + 1)/6
for i in range(10, 15):
    u_2[i] = (random.uniform(0,1) + 2)/6
for i in range(15, 20):
    u_2[i] = (random.uniform(0,1) + 3)/6
for i in range(20, 25):
    u_2[i] = (random.uniform(0,1) + 4)/6
for i in range(25, n):
    u_2[i] = (random.uniform(0,1) + 5)/6

In [316]:
u1_star = np.empty(n)
for i in range(n):
    u1_star[i] = u_1[int(permutation_0[i])-1]

In [317]:
u2_star = np.empty(n)
for i in range(n):
    u2_star[i] = u_2[int(permutation_1[i])-1]

In [318]:
u1_star

array([0.09661586, 0.02673494, 0.21705264, 0.92437118, 0.53439544,
       0.85708906, 0.54012969, 0.55654599, 0.55969614, 0.98666117,
       0.81578118, 0.43387691, 0.18035682, 0.71029848, 0.31900815,
       0.83855383, 0.99010931, 0.71235229, 0.00604812, 0.37210675,
       0.09726877, 0.35000894, 0.42215359, 0.48874684, 0.08780717,
       0.18918327, 0.58270905, 0.79993215, 0.309156  , 0.79839533])

In [319]:
u2_star

array([0.10476445, 0.12541951, 0.19689044, 0.27854193, 0.34625461,
       0.15203825, 0.47805064, 0.41276907, 0.58064316, 0.39101017,
       0.17950508, 0.26656009, 0.05463858, 0.37522927, 0.10948266,
       0.28263589, 0.62066914, 0.63215279, 0.76430405, 0.93062547,
       0.84506709, 0.78354633, 0.93048036, 0.9436737 , 0.80255974,
       0.74473802, 0.57570742, 0.8648663 , 0.60598781, 0.7305536 ])