In [73]:
import numpy as np
import random
from scipy.stats import norm

In [241]:
volatility_annual = 0.25
volatility_daily = volatility_annual/np.sqrt(250)
current_return = 0.01
alpha = 0.06
Lambda = 0.01
beta = 0.9
omega = (volatility_daily ** 2) * (1 - alpha - beta) - (Lambda ** 2) * alpha
significance_level = [0.1, 1, 5, 10]
n = 10000

In [242]:
sim_1 = np.empty(n)
for i in range(n):
    sim_1[i] = norm.ppf(random.uniform(0,1))
sim_2 = np.empty(n)
for i in range(n):
    sim_2[i] = norm.ppf(random.uniform(0,1))
sim_3 = np.empty(n)
for i in range(n):
    sim_3[i] = norm.ppf(random.uniform(0,1))
sim_4 = np.empty(n)
for i in range(n):
    sim_4[i] = norm.ppf(random.uniform(0,1))
sim_5 = np.empty(n)
for i in range(n):
    sim_5[i] = norm.ppf(random.uniform(0,1))
sim_6 = np.empty(n)
for i in range(n):
    sim_6[i] = norm.ppf(random.uniform(0,1))
sim_7 = np.empty(n)
for i in range(n):
    sim_7[i] = norm.ppf(random.uniform(0,1))
sim_8 = np.empty(n)
for i in range(n):
    sim_8[i] = norm.ppf(random.uniform(0,1))
sim_9 = np.empty(n)
for i in range(n):
    sim_9[i] = norm.ppf(random.uniform(0,1))
sim_10 = np.empty(n)
for i in range(n):
    sim_10[i] = norm.ppf(random.uniform(0,1))

In [243]:
sim_1_constant_vol = np.empty(n)
for i in range(n):
    sim_1_constant_vol[i] = sim_1[i] * volatility_daily
sim_2_constant_vol = np.empty(n)
for i in range(n):
    sim_2_constant_vol[i] = sim_2[i] * volatility_daily
sim_3_constant_vol = np.empty(n)
for i in range(n):
    sim_3_constant_vol[i] = sim_3[i] * volatility_daily
sim_4_constant_vol = np.empty(n)
for i in range(n):
    sim_4_constant_vol[i] = sim_4[i] * volatility_daily
sim_5_constant_vol = np.empty(n)
for i in range(n):
    sim_5_constant_vol[i] = sim_5[i] * volatility_daily
sim_6_constant_vol = np.empty(n)
for i in range(n):
    sim_6_constant_vol[i] = sim_6[i] * volatility_daily
sim_7_constant_vol = np.empty(n)
for i in range(n):
    sim_7_constant_vol[i] = sim_7[i] * volatility_daily
sim_8_constant_vol = np.empty(n)
for i in range(n):
    sim_8_constant_vol[i] = sim_8[i] * volatility_daily
sim_9_constant_vol = np.empty(n)
for i in range(n):
    sim_9_constant_vol[i] = sim_9[i] * volatility_daily
sim_10_constant_vol = np.empty(n)
for i in range(n):
    sim_10_constant_vol[i] = sim_10[i] * volatility_daily

In [244]:
ten_day_log_return_constant_vol = np.empty(n)
for i in range(n):
    ten_day_log_return_constant_vol[i] = sim_1_constant_vol[i] + sim_2_constant_vol[i] + sim_3_constant_vol[i] + sim_4_constant_vol[i] + sim_5_constant_vol[i] + sim_6_constant_vol[i] + sim_7_constant_vol[i] + sim_8_constant_vol[i] + sim_9_constant_vol[i] + sim_10_constant_vol[i] 

In [245]:
sim_1_GARCH_pos = np.empty(n)
for i in range(n):
    sim_1_GARCH_pos[i] = omega + (alpha * ((current_return - Lambda) ** 2)) + beta * (volatility_daily ** 2)

In [246]:
sim_1_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_1_GARCH_vol_pos[i] = sim_1[i] * np.sqrt(sim_1_GARCH_pos[i])

In [247]:
sim_2_GARCH_pos = np.empty(n)
for i in range(n):
    sim_2_GARCH_pos[i] = omega + (alpha * ((sim_1_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_1_GARCH_pos[i]

In [248]:
sim_2_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_2_GARCH_vol_pos[i] = sim_2[i] * np.sqrt(sim_2_GARCH_pos[i])

In [249]:
sim_3_GARCH_pos = np.empty(n)
for i in range(n):
    sim_3_GARCH_pos[i] = omega + (alpha * ((sim_2_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_2_GARCH_pos[i]

In [250]:
sim_3_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_3_GARCH_vol_pos[i] = sim_3[i] * np.sqrt(sim_3_GARCH_pos[i])

In [251]:
sim_4_GARCH_pos = np.empty(n)
for i in range(n):
    sim_4_GARCH_pos[i] = omega + (alpha * ((sim_3_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_3_GARCH_pos[i]

In [252]:
sim_4_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_4_GARCH_vol_pos[i] = sim_4[i] * np.sqrt(sim_4_GARCH_pos[i])

In [253]:
sim_5_GARCH_pos = np.empty(n)
for i in range(n):
    sim_5_GARCH_pos[i] = omega + (alpha * ((sim_4_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_4_GARCH_pos[i]

In [254]:
sim_5_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_5_GARCH_vol_pos[i] = sim_5[i] * np.sqrt(sim_5_GARCH_pos[i])

In [255]:
sim_6_GARCH_pos = np.empty(n)
for i in range(n):
    sim_6_GARCH_pos[i] = omega + (alpha * ((sim_5_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_5_GARCH_pos[i]

In [256]:
sim_6_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_6_GARCH_vol_pos[i] = sim_6[i] * np.sqrt(sim_6_GARCH_pos[i])

In [257]:
sim_7_GARCH_pos = np.empty(n)
for i in range(n):
    sim_7_GARCH_pos[i] = omega + (alpha * ((sim_6_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_6_GARCH_pos[i]

In [258]:
sim_7_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_7_GARCH_vol_pos[i] = sim_7[i] * np.sqrt(sim_7_GARCH_pos[i])

In [259]:
sim_8_GARCH_pos = np.empty(n)
for i in range(n):
    sim_8_GARCH_pos[i] = omega + (alpha * ((sim_7_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_7_GARCH_pos[i]

In [260]:
sim_8_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_8_GARCH_vol_pos[i] = sim_8[i] * np.sqrt(sim_8_GARCH_pos[i])

In [261]:
sim_9_GARCH_pos = np.empty(n)
for i in range(n):
    sim_9_GARCH_pos[i] = omega + (alpha * ((sim_8_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_8_GARCH_pos[i]

In [262]:
sim_9_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_9_GARCH_vol_pos[i] = sim_9[i] * np.sqrt(sim_9_GARCH_pos[i])

In [263]:
sim_10_GARCH_pos = np.empty(n)
for i in range(n):
    sim_10_GARCH_pos[i] = omega + (alpha * ((sim_9_GARCH_vol_pos[i] - Lambda) ** 2)) + beta * sim_9_GARCH_pos[i]

In [264]:
sim_10_GARCH_vol_pos = np.empty(n)
for i in range(n):
    sim_10_GARCH_vol_pos[i] = sim_10[i] * np.sqrt(sim_10_GARCH_pos[i])

In [265]:
ten_day_log_return_GARCH_vol_pos = np.empty(n)
for i in range(n):
    ten_day_log_return_GARCH_vol_pos[i] = sim_1_GARCH_vol_pos[i] + sim_2_GARCH_vol_pos[i] + sim_3_GARCH_vol_pos[i] + sim_4_GARCH_vol_pos[i] + sim_5_GARCH_vol_pos[i] + sim_6_GARCH_vol_pos[i] + sim_7_GARCH_vol_pos[i] + sim_8_GARCH_vol_pos[i] + sim_9_GARCH_vol_pos[i] + sim_10_GARCH_vol_pos[i] 

In [266]:
sim_1_GARCH_neg = np.empty(n)
for i in range(n):
    sim_1_GARCH_neg[i] = omega + (alpha * ((-current_return - Lambda) ** 2)) + beta * (volatility_daily ** 2)

In [267]:
sim_1_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_1_GARCH_vol_neg[i] = sim_1[i] * np.sqrt(sim_1_GARCH_neg[i])

In [268]:
sim_2_GARCH_neg = np.empty(n)
for i in range(n):
    sim_2_GARCH_neg[i] = omega + (alpha * ((sim_1_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_1_GARCH_neg[i]

In [269]:
sim_2_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_2_GARCH_vol_neg[i] = sim_2[i] * np.sqrt(sim_2_GARCH_neg[i])

In [270]:
sim_3_GARCH_neg = np.empty(n)
for i in range(n):
    sim_3_GARCH_neg[i] = omega + (alpha * ((sim_2_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_2_GARCH_neg[i]

In [271]:
sim_3_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_3_GARCH_vol_neg[i] = sim_3[i] * np.sqrt(sim_3_GARCH_neg[i])

In [272]:
sim_4_GARCH_neg = np.empty(n)
for i in range(n):
    sim_4_GARCH_neg[i] = omega + (alpha * ((sim_3_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_3_GARCH_neg[i]

In [273]:
sim_4_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_4_GARCH_vol_neg[i] = sim_4[i] * np.sqrt(sim_4_GARCH_neg[i])

In [274]:
sim_5_GARCH_neg = np.empty(n)
for i in range(n):
    sim_5_GARCH_neg[i] = omega + (alpha * ((sim_4_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_4_GARCH_neg[i]

In [275]:
sim_5_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_5_GARCH_vol_neg[i] = sim_5[i] * np.sqrt(sim_5_GARCH_neg[i])

In [276]:
sim_6_GARCH_neg = np.empty(n)
for i in range(n):
    sim_6_GARCH_neg[i] = omega + (alpha * ((sim_5_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_5_GARCH_neg[i]

In [277]:
sim_6_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_6_GARCH_vol_neg[i] = sim_6[i] * np.sqrt(sim_6_GARCH_neg[i])

In [278]:
sim_7_GARCH_neg = np.empty(n)
for i in range(n):
    sim_7_GARCH_neg[i] = omega + (alpha * ((sim_6_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_6_GARCH_neg[i]

In [279]:
sim_7_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_7_GARCH_vol_neg[i] = sim_7[i] * np.sqrt(sim_7_GARCH_neg[i])

In [280]:
sim_8_GARCH_neg = np.empty(n)
for i in range(n):
    sim_8_GARCH_neg[i] = omega + (alpha * ((sim_7_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_7_GARCH_neg[i]

In [281]:
sim_8_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_8_GARCH_vol_neg[i] = sim_8[i] * np.sqrt(sim_8_GARCH_neg[i])

In [282]:
sim_9_GARCH_neg = np.empty(n)
for i in range(n):
    sim_9_GARCH_neg[i] = omega + (alpha * ((sim_8_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_8_GARCH_neg[i]

In [283]:
sim_9_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_9_GARCH_vol_neg[i] = sim_9[i] * np.sqrt(sim_9_GARCH_neg[i])

In [284]:
sim_10_GARCH_neg = np.empty(n)
for i in range(n):
    sim_10_GARCH_neg[i] = omega + (alpha * ((sim_9_GARCH_vol_neg[i] - Lambda) ** 2)) + beta * sim_9_GARCH_neg[i]

In [285]:
sim_10_GARCH_vol_neg = np.empty(n)
for i in range(n):
    sim_10_GARCH_vol_neg[i] = sim_10[i] * np.sqrt(sim_10_GARCH_neg[i])

In [286]:
ten_day_log_return_GARCH_vol_neg = np.empty(n)
for i in range(n):
    ten_day_log_return_GARCH_vol_neg[i] = sim_1_GARCH_vol_neg[i] + sim_2_GARCH_vol_neg[i] + sim_3_GARCH_vol_neg[i] + sim_4_GARCH_vol_neg[i] + sim_5_GARCH_vol_neg[i] + sim_6_GARCH_vol_neg[i] + sim_7_GARCH_vol_neg[i] + sim_8_GARCH_vol_neg[i] + sim_9_GARCH_vol_neg[i] + sim_10_GARCH_vol_neg[i] 

In [287]:
constant_vol_VaR = np.empty(4)
for i in range(4):
    constant_vol_VaR[i] = -np.percentile(ten_day_log_return_constant_vol, significance_level[i])

In [288]:
constant_vol_VaR

array([0.1515162 , 0.11439224, 0.08166453, 0.06457972])

In [289]:
pos_GARCH_vol_VaR = np.empty(4)
for i in range(4):
    pos_GARCH_vol_VaR[i] = -np.percentile(ten_day_log_return_GARCH_vol_pos, significance_level[i])

In [290]:
pos_GARCH_vol_VaR

array([0.17540931, 0.12109754, 0.08189451, 0.06279208])

In [291]:
neg_GARCH_vol_VaR = np.empty(4)
for i in range(4):
    neg_GARCH_vol_VaR[i] = -np.percentile(ten_day_log_return_GARCH_vol_neg, significance_level[i])

In [292]:
neg_GARCH_vol_VaR

array([0.18211191, 0.12625237, 0.08527506, 0.06542346])

In [304]:
AGARCH = [sim_1_GARCH_vol_pos[0], sim_2_GARCH_vol_pos[0], sim_3_GARCH_vol_pos[0], sim_4_GARCH_vol_pos[0], sim_5_GARCH_vol_pos[0], sim_6_GARCH_vol_pos[0], sim_7_GARCH_vol_pos[0], sim_8_GARCH_vol_pos[0], sim_9_GARCH_vol_pos[0], sim_10_GARCH_vol_pos[0]] 
%store AGARCH

Stored 'AGARCH' (list)
